services:
  mysql:
    container_name: 'mscourse-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mscoursedb'
      - 'MYSQL_PASSWORD=mscourse123'
      - 'MYSQL_ROOT_PASSWORD=mscourse123'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'